README.md
crates/types/src/v1alpha1/wasmcloud_host_config.rs
sample.yaml

Add documentation on how to use the `registryCredentialsSecret` to enable wasmCloud hosts to pull from a private registry.
Also add comments to each of the CRD fields outlining what each field does.
next

chore: add docs on how to use the `registryCredentialsSecret` option

---

src/controller.rs

In wasmCloud 0.81.0 we deprecated the old `OCI_REGISTRY` variables in favor of prefixing them with `WASMCLOUD`. 0.82.0 fully removed those variables, so this updates the controller to use the new variables with an eye towards wasmCloud 1.0 compatibility.
next
This removes support for hosts < 0.81.0 using custom registries, which should be fine.

fix: use the correct OCI registry environment variables for newer hosts

---

Cargo.lock
Cargo.toml
src/main.rs

The use of `atty` is no longer necessary, or desirable, so let's make use of the [standard library functionality introduced in 1.70](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#isterminal) instead.
https://github.com/wasmCloud/wasmcloud-operator/security/dependabot/1

fix: Address GHSA-g98v-hv3f-hcfr

---

.github/dependency-review-config.yml
.github/workflows/dependency-review.yml

GitHub recently announced the addition of [OpenSSF Scorecard support in the `dependency-review` GitHub Action](https://github.blog/changelog/2024-03-20-openssf-scorecard-info-is-now-available-in-the-dependency-review-action/), which brought this action to my attention.
Having looked at it, this looks like it could be a useful addition for the PR pipeline in order to help maintain awareness of the state of dependencies that are being introduced/changed.

chore: Add dependency-review workflow for pull requests

---

Cargo.lock
Cargo.toml
Dockerfile.local
crates/types/src/v1alpha1/wasmcloud_host_config.rs
sample.yaml
src/controller.rs

This refactors the WasmCloudHostConfig CRD so that it has a single field (`schedulingOptions`) for configuring how the underlying Pods are scheduled in Kubernetes. This includes:
* Relocating the `daemonset` option to this new field
* Relocating the `resources` option to this new field
* Adding a new `pod_template_additions` field that allows you to set any valid option in a `PodSpec`
Doing so allows cluster operators to do things like set node affinity and node selector rules, along with any other valid PodSpec option. The only thing that cannot be done is adding additional containers to the pod, since that is all handled by the controller. We could look at exposing that option if users want to be able to add additional sidecars.
next
Tested locally in kind by setting `daemonset: true` …

feat: enable additional scheduling options for wasmCloud host pods

---

Cargo.lock
Cargo.toml
README.md
charts/wasmcloud-operator/Chart.yaml
charts/wasmcloud-operator/templates/deployment.yaml
deploy/base/deployment.yaml
deploy/local/local-registry.yaml
hack/run-kind-cluster.sh
src/config.rs
src/controller.rs
src/lib.rs
src/main.rs
src/resources/application.rs
src/services.rs

One advantage of wasmCloud applications is that we always know what components make up an application and therefore can intelligently make decisions based on what interfaces we're using. This makes it much easier for software like the operator to take particular actions based on the contents of an application manifest.
This change adds an additional set of reconciliations we can perform on a per-lattice basis to automatically create Kubernetes Services for applications that deploy a httpserver component. The operator uses a NATS consumer that watches for manifest deploy and undeploy events and triggers a reconciliation on a managed Service. Right now this is restricted only to `daemonscalers`, since we do not have to do any bookeeping on where components are deployed if they are running …

feat: automatically create Kubernetes Services for apps using a httpserver component

---

Cargo.lock
Cargo.toml
crates/types/Cargo.toml
crates/types/src/v1alpha1/wasmcloud_host_config.rs
sample.yaml
src/controller.rs
src/services.rs

wasmCloud 1.0 fully converts over to using components among other large changes, so we need to rework the operator to account for it. 1.0 is still in the works, so this updates the operator to depend on wasmCloud 1.0 libraries along with refactoring the service creation code to use the updated application manifest format.
Once this is in we will likely cut a 0.2.0 pre-release and wait for an actual release until wasmCloud 1.0.0 and wadm 0.11 are out.
This also adds a new field to the CRD so that you can specify the full image reference instead of just the version. The `image` parameter takes precedence.
0.2.0

feat: rework the operator for wasmCloud 1.0 compatibility

---

Cargo.lock
Cargo.toml
README.md
deploy/base/deployment.yaml
sample.yaml

This bumps both the version of the operator and the default host version in the example to 1.0. Also updates the README to use the released wadm chart

feat(*): Bumps to 0.2 for wasmcloud 1.0 support

---

src/services.rs

While working on something somewhat related, I noticed that third-party software that was trying to connect to the Services we create for wasmCloud applications could not do so.
After some spelunking, it turned out that the software in question was looking for the `Ready` condition of the `Endpoints` section of a given `EndpointSlice`, which was previously missing. 
This fixes that.

Add conditions to Endpoints part of the EndpointSlices reflecting wadm application Service entries

---

README.md
deploy/base/deployment.yaml
sample.yaml

chore: update README with latest version, example policy topic

---

hack/run-kind-cluster.sh
sample.yaml
src/controller.rs

This fix omits the preset NATS leaf node port `7422` from being automatically set if the `natsAddress` field is set in the CRD. This allows you to specify the port if it is not using the default at the cost of making it required.
next
Tested locally with kind connected to a NATS cluster serving leaf node connections on a different port than the default

fix: allow nats address to include a port

---

Cargo.lock
crates/types/Cargo.toml
crates/types/src/v1alpha1/wasmcloud_host_config.rs
src/controller.rs

We already have the option to override the wasmCloud host image, let's add one for the NATS leaf that gets deployed alongside the wasmCloud host.

feat: Add option to customize NATS leaf node image

---

Cargo.lock
Cargo.toml
README.md

In light of #42, we should also add instructions on how to use these options, which this does.
I could be convinced that these should be part of the main example, but it's a little iffy to include them as comments because they can easily get lost in the noise.

chore: Bump the operator version, update README with instructions on how to override images

---

Cargo.lock
Cargo.toml
src/controller.rs
src/resources/application.rs
src/services.rs

Switching us from using `wash-lib` to the newly available `wadm-client` and `wadm-types` crates instead, which cleans things up nicely!
cc @thomastaylor312

feat: Use wadm-client and wadm-types crates for wadm interactions

---

src/resources/application.rs

This addresses some tech debt from when the operator was originally created.
Fixes #50

fix: Use new struct to combine Manifest and Status structs for get_application

---

Cargo.lock
Cargo.toml
src/services.rs

This adapts the operator to the changes from https://github.com/wasmCloud/wadm/pull/310, it needs the changes to be released in the `wadm` crate before merging.

chore: Adapt to the new wadm_events stream hierarchy

---

src/resources/application.rs

The changes to no longer require a version as part of the manifest had the inadvertent effect of causing the patch operations to fail when the local manifest being used to update does not have a version set since we fetch the current manifest and layer the patch on top of that.
There's opportunity to future improvements around attempting to pre-empt the need to patch an application at all in case the contents have not changed at all.

fix: Improve handling for patching existing applications

---

crates/types/src/v1alpha1/wasmcloud_host_config.rs
src/controller.rs
src/lib.rs

Fixes https://github.com/wasmCloud/wasmcloud-operator/issues/69
Requires https://github.com/wasmCloud/wasmCloud/pull/2468
Allow passing one or more certificate authorities into wasmcloud via configmaps & secrets.
Example authorities:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: org-authorities
data:
dontmountme: |
-----BEGIN CERTIFICATE-----
Custom CA certificate bundle.
-----END CERTIFICATE-----
root.crt: |
-----BEGIN CERTIFICATE-----
Custom CA certificate bundle.
-----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
name: email-authorities
stringData:
email.crt: |
-----BEGIN CERTIFICATE-----
Custom CA certificate bundle.
-----END CERTIFICATE-----
notifications.crt: |
-----BEGIN CERTIFICATE-----
Custom CA certificate bundle.
-----END CERTIFICATE-----
```
We pass …

feat: Certificate Authorities to wasmcloud host

---

charts/wasmcloud-operator/Chart.yaml
deploy/base/deployment.yaml

In preparation for the [release of `0.3.2`](https://github.com/wasmCloud/wasmcloud-operator/releases/tag/v0.3.2), let's update both of the deployment artifacts to reference the latest version.

chore: Bump wasmcloud-operator version references in deployment artifacts

---

Cargo.lock
Cargo.toml
src/main.rs

Since the upstream decided to change things around in https://github.com/open-telemetry/opentelemetry-rust/pull/1199, this ended up breaking dependabot bot updates: https://github.com/wasmCloud/wasmcloud-operator/network/updates/859461387
This updates opentelemetry (and the related dependencies/ecosystem) to 0.21 so that we can get dependabot back to working.

fix: Upgrade opentelemetry to 0.21

---

Cargo.lock
Cargo.toml
crates/types/Cargo.toml
crates/types/src/v1alpha1/wasmcloud_host_config.rs
examples/full-config/wasmcloud-annotated.yaml
src/controller.rs
src/openapi.rs
src/services.rs

Since the features support is rolling out in the wasmCloud host, we should also add support to use it in the operator.

feat: Add support for configuring wasmCloud Secrets

---

examples/quickstart/hello-world-application.yaml

This will allow the k8s operator to automatically create services. This shouldn't be required in the future when the operator supports the spreadscaler for httpserver providers as well.

fix(examples): add daemonscaler to httpserver

---

Cargo.lock
Cargo.toml
crates/types/Cargo.toml
crates/types/src/v1alpha1/wasmcloud_host_config.rs
examples/full-config/wasmcloud-annotated.yaml
src/controller.rs

⚠️  Needs wasmcloud 1.2 https://github.com/wasmCloud/wasmCloud/releases/tag/v1.2.0-rc.1
Configures the maximum amount of bytes that a component can allocate.
https://github.com/wasmCloud/wasmCloud/pull/2713

feat: Configure max component memory

---

.github/workflows/build.yml
Dockerfile.wolfi

feat: Add wolfi-based image

---

Cargo.lock
Cargo.toml
src/main.rs

This adds a rudimentary version flag for checking the version of wasmcloud-operator.
The chosen values for representing the flag align with `clap` defaults ([`version`](https://docs.rs/clap/latest/clap/struct.Command.html#method.version), [`long_version`](https://docs.rs/clap/latest/clap/struct.Command.html#method.long_version)) in case we wanted to use `clap` in the future, for now it felt unnecessary for adding support for this flag alone.

feat: Add rudimentary version flag

---

deploy/base/deployment.yaml

We were pinned to an old version so when I deployed as directed in the README it deployed an old version without the new features I needed

chore(yaml): Update version in the kustomize yaml

---

examples/quickstart/hello-world-application.yaml

The hello world example used 127.0.0.1 as the address for the http provider, but that causes networking issues when running on Kubernetes (connections via service name within the cluster don't work). Fixing here and commenting to explain the requirement.

fix(examples): change http provider address for hello world app
