- .github/workflows/chart.yaml
- charts/wasmcloud-operator/.helmignore
- charts/wasmcloud-operator/Chart.yaml
- charts/wasmcloud-operator/ct.yaml
- charts/wasmcloud-operator/templates/_helpers.tpl
- charts/wasmcloud-operator/templates/cluster-role.yaml
- charts/wasmcloud-operator/templates/deployment.yaml
- charts/wasmcloud-operator/templates/service.yaml
- charts/wasmcloud-operator/templates/serviceaccount.yaml
- charts/wasmcloud-operator/templates/tests/test-connection.yaml
- charts/wasmcloud-operator/values.yaml
Add helm chart to make it easy to deploy the `wasmcloud-operator`
> feat: Add helm chart

- .github/workflows/chart.yaml
To avoid conflicting names with the containers and potential confusion, this moves charts to be published under a separate namespace (`charts/<chart-name>`).
> chore: Update charts to be published under separate namespace

- Cargo.lock
- Cargo.toml
- LICENSE
- sample.yaml
- src/resources/application.rs
- src/services.rs
This fixes a few Rust-y things and dedupes some code I found while addressing clippy errors
> ref(*): Refactors some copied code and bumps version

- README.md
Add instructions for using the wadm Helm chart to the readme.
> Add wadm instructions to readme

- README.md
Let's help the potential reader with some links in case the Operator README is their first contact with wasmCloud.
> Fix up some README typos and add relevant links

- Cargo.lock
- Cargo.toml
Update to use the latest wasmCloud 1.0 compatible versions of wadm and wash-lib.
0.2.0
Tested locally in kind and everything worked!
> chore: update wadm and wash-lib to the latest released versions

- charts/wasmcloud-operator/Chart.yaml
- charts/wasmcloud-operator/templates/cluster-role.yaml
Brings permissions changes from #14 to the chart
> Add Pods and EndpointSlices permissions to wasmcloud-operator ClusterRole

- .github/workflows/chart.yaml
Currently we're not using the full path, which makes `helm package` fail
> Use the full chart path for helm package

- Cargo.lock
- Cargo.toml
- crates/types/Cargo.toml
- crates/types/src/v1alpha1/wasmcloud_host_config.rs
- sample.yaml
- src/controller.rs
Add additional host options for the policy service, allowing insecure registries and pulling the latest tag of an OCI ref.
next
Tested locally in a kind cluster
> feat: add additional host configuration options for images, policy

- Cargo.lock
- Cargo.toml
> chore: bump wasmcloud-operator version for 0.2.2 release

- Cargo.lock
- Cargo.toml
> chore: prepare for 0.2.3 release

- charts/wasmcloud-operator/Chart.yaml
- deploy/base/deployment.yaml
> chore: update kustomization and Helm chart to default to 0.2.3

- README.md
Examples added in #43 did not include the correct highlighting, which makes the examples harder to read than need be.
> chore: Update image customization examples to include YAML syntax higlighting

- .github/dependabot.yml
While reviewing a GitHub Action run, I noticed that we were using an old version of the checkout action, so I figured we should add dependabot in to the repository to help us keep dependencies updated.
> chore: Add dependabot configuration for dependency updates

- Cargo.lock
- Cargo.toml
This is to prep the 0.3.0 release
> chore: Tag wasmcloud-operator 0.3.0

- Cargo.lock
- Cargo.toml
This releases the changes from #65
> chore: Bump wasmcloud-operator to 0.3.1

- src/controller.rs
Just a couple of things that keep getting highlighted in the editor
> chore: Address Clippy lints and nested-ifs

- charts/wasmcloud-operator/Chart.yaml
Incorporates all of the changes from the latest release (`0.4.0`)
> chore: Bump wasmcloud-operator chart appVersion

- MAINTAINERS.md
> chore: List maintainer affiliations

- crates/types/Cargo.toml
> chore(wasmcloud-operator-types): Remove unused `serde_json` dependency

- charts/wasmcloud-operator/Chart.yaml
- charts/wasmcloud-operator/templates/_helpers.tpl
- charts/wasmcloud-operator/values.yaml
Support all [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) and additional labels to add to all resources
> feat(helm): Kubernetes labels

- SECURITY.md
> chore: Add Security Policy with link to the main repository
